# Generated by Django 3.1.5 on 3.2.12 on 2022-04-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='secs',
        ),
    ]
